In [376]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json

In [377]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [378]:
df1 = pd.read_csv('laptops.csv')
df2 = pd.read_csv('smartphones.csv')
df3 = pd.read_csv('tablets.csv')

In [379]:
df1.dtypes

category                     object
name_card                    object
price                       float64
price_old                   float64
price_installment           float64
rating_card                 float64
reviews_card                float64
name_seller                  object
rating_seller               float64
URL                          object
cpu                          object
ssd_capacity                float64
gpu_full_name                object
os                           object
screen_diagonal             float64
ram                         float64
auto_time                   float64
weight_kg                   float64
matrix                       object
ram_type                     object
case_material                object
cpu_model                    object
processor_brand              object
ghz_processor               float64
processor_cores             float64
screen_size                  object
brightness                  float64
touch_screen                 object
battery_capacity            float64
screen_coating               object
gpu_type                     object
brand_graphic_proccessor     object
storage_type                 object
hz_screen                   float64
web_camera                  float64
brand                        object
video_memory                float64
chipset                      object
hdd_capacity                float64
dtype: object

In [380]:
df1.isnull().sum()

category                       0
name_card                    979
price                       2873
price_old                   2873
price_installment            998
rating_card                 3000
reviews_card                2976
name_seller                  979
rating_seller               1181
URL                            0
cpu                          852
ssd_capacity                 624
gpu_full_name               1058
os                           680
screen_diagonal              587
ram                          464
auto_time                   2861
weight_kg                    948
matrix                      1076
ram_type                     986
case_material               1592
cpu_model                    455
processor_brand              631
ghz_processor                977
processor_cores              776
screen_size                  688
brightness                  3408
touch_screen                1993
battery_capacity            2065
screen_coating              1136
gpu_type                    1131
brand_graphic_proccessor    1030
storage_type                 874
hz_screen                   1323
web_camera                  1955
brand                       3325
video_memory                4098
chipset                     3763
hdd_capacity                5143
dtype: int64

In [381]:
df1.sample(5)

,category,name_card,price,price_old,price_installment,rating_card,reviews_card,name_seller,rating_seller,URL,cpu,ssd_capacity,gpu_full_name,os,screen_diagonal,ram,auto_time,weight_kg,matrix,ram_type,case_material,cpu_model,processor_brand,ghz_processor,processor_cores,screen_size,brightness,touch_screen,battery_capacity,screen_coating,gpu_type,brand_graphic_proccessor,storage_type,hz_screen,web_camera,brand,video_memory,chipset,hdd_capacity
3747,laptop,MSI Vector A18 HX A9WIG-076US Игровой ноутбук ...,2260154.0,3286705.0,188347.0,5.0,2.0,GlobalZon,4.8,https://www.ozon.kz/product/msi-vector-a18-hx-...,AMD Ryzen 9 9955HX,2048.0,NVIDIA GeForce RTX 5080 для ноутбуков (16 Гб),Windows Pro,18.0,64.0,5.0,3.60,IPS,DDR5,"Алюминий, Пластик",AMD Ryzen 9,AMD,5.4,16.0,2560x1600,500.0,Нет,99.9,Матовое,Дискретная,NVIDIA,SSD,240.0,2.0,MSI,16.0,NaN,NaN
5185,laptop,Apple Ноутбук MacBook Air 13 M2 2022 16/256 GB...,625210.0,873648.0,52101.0,5.0,212.0,MacStore,4.9,https://www.ozon.kz/product/apple-noutbuk-macb...,"Apple M2 (8C CPU, 8C GPU)",256.0,NaN,MacOS,13.6,16.0,20.0,1.24,IPS,DDR4,"Алюминий, Стекло",Apple M2,Apple,3.5,8.0,2560x1664,NaN,Нет,NaN,Глянцевое,NaN,Apple,SSD,NaN,NaN,Apple,NaN,NaN,NaN
269,laptop,"Acer Aspire Go 15 AG15-32P-39R Ноутбук 15.6"", ...",NaN,NaN,27209.0,NaN,NaN,Space Laptops,4.9,https://www.ozon.kz/product/acer-aspire-go-15-...,Intel Core 3 N355,128.0,Intel UHD Graphics,Windows Home,15.6,8.0,NaN,1.75,IPS,DDR5,Пластик,Intel Core 3,Intel,1.9,8.0,1920x1080,300.0,Нет,50.0,Матовое,Встроенная,Intel,SSD,60.0,1.0,Acer,NaN,NaN,NaN
263,laptop,Lenovo Legion Pro 7 16IAX10H Игровой ноутбук 1...,NaN,NaN,351677.0,NaN,NaN,Бук Вам в Дом,4.9,https://www.ozon.kz/product/lenovo-legion-pro-...,Intel Core Ultra 9 275HX,2048.0,NVIDIA GeForce RTX 5090 для ноутбуков (24 Гб),Windows Home,16.0,64.0,6.0,2.60,OLED,DDR5,NaN,Intel Core Ultra 9,Intel,2.1,24.0,2560x1600,500.0,Нет,NaN,Глянцевое,Дискретная,NVIDIA,SSD,240.0,NaN,Lenovo,24.0,Intel,NaN
2904,laptop,"Machenike S15 Quazar S Игровой ноутбук 15.6"", ...",NaN,NaN,45106.0,4.9,331.0,Machenike - авториз...,4.8,https://www.ozon.kz/product/machenike-s15-quaz...,Intel Core i5-12450H,512.0,NVIDIA GeForce RTX 3050 для ноутбуков (4 Гб),Без системы,15.6,16.0,NaN,2.50,IPS,"DDR4, GDDR6",Пластик,Intel Core i5,Intel,4.4,8.0,1920x1080,250.0,Нет,41.0,Матовое,Дискретная,NVIDIA,SSD,144.0,1.0,NaN,4.0,NaN,NaN

In [382]:
# Диагностика столбцов для возможного удаления
n_rows = len(df1)
summary = pd.DataFrame({
    'null_count': df1.isna().sum(),
    'null_pct': (df1.isna().mean() * 100).round(2),
    'nunique': df1.nunique(dropna=False),
    'dtype': df1.dtypes.astype(str)
}).sort_values('null_pct', ascending=False)

print('Rows:', n_rows)
print('Columns:', df1.shape[1])
print('\nTop columns by null %:')
print(summary.head(20))

const_cols = summary[summary['nunique'] <= 1].index.tolist()
high_null_cols = summary[summary['null_pct'] >= 70].index.tolist()

print('\nConstant/near-constant cols (nunique <= 1):', const_cols)
print('High-null cols (>=70% NaN):', high_null_cols)

Rows: 5376
Columns: 39

Top columns by null %:
                  null_count  null_pct  nunique    dtype
hdd_capacity            5143     95.67       18  float64
video_memory            4098     76.23       13  float64
chipset                 3763     70.00       19   object
brightness              3408     63.39       31  float64
brand                   3325     61.85       60   object
rating_card             3000     55.80       32  float64
reviews_card            2976     55.36      258  float64
price                   2873     53.44     2408  float64
price_old               2873     53.44     2341  float64
auto_time               2861     53.22       68  float64
battery_capacity        2065     38.41      144  float64
touch_screen            1993     37.07        3   object
web_camera              1955     36.37       12  float64
case_material           1592     29.61       85   object
hz_screen               1323     24.61       14  float64
rating_seller           1181     21.97       14  float64
screen_coating          1136     21.13        4   object
gpu_type                1131     21.04        4   object
matrix                  1076     20.01       12   object
gpu_full_name           1058     19.68      165   object

Constant/near-constant cols (nunique <= 1): ['category']
High-null cols (>=70% NaN): ['hdd_capacity', 'video_memory', 'chipset']

In [383]:
df1.drop(columns=['hdd_capacity','URL','video_memory','chipset','brightness','brand'], inplace=True)

In [384]:
df1.isna().sum()

category                       0
name_card                    979
price                       2873
price_old                   2873
price_installment            998
rating_card                 3000
reviews_card                2976
name_seller                  979
rating_seller               1181
cpu                          852
ssd_capacity                 624
gpu_full_name               1058
os                           680
screen_diagonal              587
ram                          464
auto_time                   2861
weight_kg                    948
matrix                      1076
ram_type                     986
case_material               1592
cpu_model                    455
processor_brand              631
ghz_processor                977
processor_cores              776
screen_size                  688
touch_screen                1993
battery_capacity            2065
screen_coating              1136
gpu_type                    1131
brand_graphic_proccessor    1030
storage_type                 874
hz_screen                   1323
web_camera                  1955
dtype: int64

In [385]:
median_col = ['price','price_old','price_installment','rating_card','reviews_card','ssd_capacity','screen_diagonal','ram',
           'auto_time','weight_kg','ghz_processor','processor_cores','battery_capacity','hz_screen']
for col in median_col:
    df1[col] = df1[col].fillna(df1[col].median())

mode_col = ['rating_seller','web_camera']
for col in mode_col:
    df1[col] = df1[col].fillna(df1[col].mode()[0])

In [386]:
cat_cols = ['name_seller','cpu','gpu_full_name','os','matrix','ram_type','case_material','cpu_model',''
            'processor_brand','screen_size','touch_screen','screen_coating', 'gpu_type', 'brand_graphic_proccessor','storage_type']
for col in cat_cols:
    df1[col] = df1[col].fillna('no_data')

In [387]:
cat_cols

['name_seller',
 'cpu',
 'gpu_full_name',
 'os',
 'matrix',
 'ram_type',
 'case_material',
 'cpu_model',
 'processor_brand',
 'screen_size',
 'touch_screen',
 'screen_coating',
 'gpu_type',
 'brand_graphic_proccessor',
 'storage_type']

In [388]:
df1.isna().sum()

category                      0
name_card                   979
price                         0
price_old                     0
price_installment             0
rating_card                   0
reviews_card                  0
name_seller                   0
rating_seller                 0
cpu                           0
ssd_capacity                  0
gpu_full_name                 0
os                            0
screen_diagonal               0
ram                           0
auto_time                     0
weight_kg                     0
matrix                        0
ram_type                      0
case_material                 0
cpu_model                     0
processor_brand               0
ghz_processor                 0
processor_cores               0
screen_size                   0
touch_screen                  0
battery_capacity              0
screen_coating                0
gpu_type                      0
brand_graphic_proccessor      0
storage_type                  0
hz_screen                     0
web_camera                    0
dtype: int64

In [389]:
df2.head()

,category,name_card,price,price_old,price_installment,rating_card,reviews_card,name_seller,rating_seller,url,article,screen_diagonal,battery_capacity,cpu,screen_size,processor_cores,ram,Characteristics.Встроенная память,main_camera,os,hz_screen,matrix,processor_brand,ghz_processor,e_sim,front_camera,type_of_frame,degree_of_protect,dimensions,weight_g,country_of_origin,case_material,android_version,brand_graphic_proccessor,video_processor,max_fps_video,brand,ios_version,harmonyos_version
0,smartphones,Xiaomi Смартфон Xiaomi Redmi Note 14 Pro+ 5G Р...,216456.0,542517.0,18038.0,4.8,322.0,SmartPhone,4.9,https://www.ozon.kz/product/xiaomi-smartfon-xi...,3.469361e+09,6.67,5110.0,Snapdragon 7s Gen3,2712x1220,8.0,8.0,256.0,200.0,Android,120.0,AMOLED,Qualcomm,2.5,eSIM+SIM,20.0,Моноблок,IP68,162.53х74.67х8.85,205.13,Китай,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,smartphones,"Смартфон A16 Pro Ростест (EAC) 16/1 ТБ, серый",54016.0,440665.0,4502.0,5.0,29.0,AMG,4.5,https://www.ozon.kz/product/smartfon-a16-pro-r...,3.689839e+09,6.80,8000.0,Dimensity 9300 Plus,3200x2400,10.0,16.0,1024.0,108.0,Android,90.0,IPS,MediaTek,3.4,SIM (без eSIM),50.0,Моноблок,IP45,155*74*8.4,200.00,Китай,"Стекло, Металл",Android 14,Qualcomm,Adreno 730,60.0,NaN,NaN,NaN
2,smartphones,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.ozon.kz/product/redmi-smartfon-8-2...,3.198104e+09,6.79,5030.0,NaN,2400x1080,8.0,8.0,256.0,108.0,Android,90.0,IPS,MediaTek,2.0,SIM (без eSIM),13.0,Моноблок,IP53,168.6 x 76.3 x 8.3,205.00,Китай,"Пластик, Стекло",Android 14,ARM,Mali-G52 MC2,30.0,Redmi,NaN,NaN
3,smartphones,"Xiaomi Смартфон Mix Flip 12/512 ГБ, фиолетовый",NaN,NaN,46191.0,4.7,9.0,Teleflow,4.9,https://www.ozon.kz/product/xiaomi-smartfon-mi...,3.323519e+09,6.86,4780.0,Snapdragon 8 Gen3,2700x1224,8.0,12.0,512.0,50.0,Android,120.0,AMOLED,Qualcomm,3.3,SIM (без eSIM),32.0,Складной,IP68,167.5x74x7.6,192.00,Китай,"Металл, Стекло",Android 14,Qualcomm,Adreno 750,NaN,NaN,NaN,NaN
4,smartphones,"Redmi Смартфон Redmi 14C Global 8/256 ГБ, сире...",NaN,NaN,4901.0,4.3,63.0,opt. marina,4.3,https://www.ozon.kz/product/redmi-smartfon-red...,2.396422e+09,6.88,5160.0,Helio G81,1640x720,8.0,8.0,256.0,50.0,Android,NaN,NaN,MediaTek,2.0,SIM (без eSIM),13.0,Моноблок,IP68,171.88*77.8*8.22,211.00,Китай,"Металл, Стекло",Android 13,NaN,NaN,30.0,Redmi,NaN,NaN

In [390]:
df2.rename(columns={'Characteristics.Встроенная память':'built-in_memory'}, inplace=True)

In [391]:
# Диагностика столбцов для возможного удаления
n_rows = len(df2)
summary = pd.DataFrame({
    'null_count': df2.isna().sum(),
    'null_pct': (df2.isna().mean() * 100).round(2),
    'nunique': df2.nunique(dropna=False),
    'dtype': df2.dtypes.astype(str)
}).sort_values('null_pct', ascending=False)

print('Rows:', n_rows)
print('Columns:', df1.shape[1])
print('\nTop columns by null %:')
print(summary.head(20))

const_cols = summary[summary['nunique'] <= 1].index.tolist()
high_null_cols = summary[summary['null_pct'] >= 70].index.tolist()

print('\nConstant/near-constant cols (nunique <= 1):', const_cols)
print('High-null cols (>=70% NaN):', high_null_cols)

Rows: 5382
Columns: 33

Top columns by null %:
                          null_count  null_pct  nunique    dtype
harmonyos_version               5318     98.81        7   object
ios_version                     5024     93.35       13   object
brand                           3811     70.81       28   object
video_processor                 1941     36.06      122   object
max_fps_video                   1935     35.95       14  float64
brand_graphic_proccessor        1607     29.86       16   object
hz_screen                       1370     25.46       10  float64
price                           1350     25.08     3171  float64
price_old                       1350     25.08     2319  float64
degree_of_protect               1003     18.64       73   object
android_version                  954     17.73       17   object
cpu                              772     14.34      228   object
e_sim                            713     13.25        4   object
ghz_processor                    581     10.80       71  float64
case_material                    562     10.44       99   object
rating_card                      530      9.85       31  float64
reviews_card                     530      9.85      524  float64
type_of_frame                    509      9.46        3   object
matrix                           476      8.84       42   object
country_of_origin                402      7.47       30   object

Constant/near-constant cols (nunique <= 1): ['category']
High-null cols (>=70% NaN): ['harmonyos_version', 'ios_version', 'brand']

In [392]:
df2.isna().sum()

category                       0
name_card                    312
price                       1350
price_old                   1350
price_installment            325
rating_card                  530
reviews_card                 530
name_seller                  312
rating_seller                315
url                            0
article                        9
screen_diagonal              117
battery_capacity             231
cpu                          772
screen_size                  285
processor_cores              209
ram                          161
built-in_memory               76
main_camera                  223
os                           131
hz_screen                   1370
matrix                       476
processor_brand              337
ghz_processor                581
e_sim                        713
front_camera                 244
type_of_frame                509
degree_of_protect           1003
dimensions                   274
weight_g                     302
country_of_origin            402
case_material                562
android_version              954
brand_graphic_proccessor    1607
video_processor             1941
max_fps_video               1935
brand                       3811
ios_version                 5024
harmonyos_version           5318
dtype: int64

In [393]:
cat_cols = df2.select_dtypes(exclude=[np.number]).columns.tolist()
cat_cols

['category',
 'name_card',
 'name_seller',
 'url',
 'cpu',
 'screen_size',
 'os',
 'matrix',
 'processor_brand',
 'e_sim',
 'type_of_frame',
 'degree_of_protect',
 'dimensions',
 'country_of_origin',
 'case_material',
 'android_version',
 'brand_graphic_proccessor',
 'video_processor',
 'brand',
 'ios_version',
 'harmonyos_version']

In [394]:
df2.drop(columns=['harmonyos_version','ios_version','brand','url','android_version'], inplace=True)

In [395]:
med_col = ['price','price_old','rating_card','reviews_card','price_installment','rating_seller','screen_diagonal','ram',
           'weight_g','built-in_memory','ghz_processor','processor_cores','battery_capacity','hz_screen','main_camera','front_camera','max_fps_video']

for col in med_col:
    df2[col] = df2[col].fillna(df2[col].median())

unk_col = ['category', 'name_seller','cpu', 'screen_size','os','matrix','processor_brand','e_sim','type_of_frame',
           'degree_of_protect','dimensions','country_of_origin','case_material','brand_graphic_proccessor','video_processor']
for col in unk_col:
    df2[col] = df2[col].fillna('no_data')

In [396]:
df2.isna().sum()

category                      0
name_card                   312
price                         0
price_old                     0
price_installment             0
rating_card                   0
reviews_card                  0
name_seller                   0
rating_seller                 0
article                       9
screen_diagonal               0
battery_capacity              0
cpu                           0
screen_size                   0
processor_cores               0
ram                           0
built-in_memory               0
main_camera                   0
os                            0
hz_screen                     0
matrix                        0
processor_brand               0
ghz_processor                 0
e_sim                         0
front_camera                  0
type_of_frame                 0
degree_of_protect             0
dimensions                    0
weight_g                      0
country_of_origin             0
case_material                 0
brand_graphic_proccessor      0
video_processor               0
max_fps_video                 0
dtype: int64

In [397]:
df3.head()

,category,name_card,price,price_old,price_installment,rating_card,reviews_card,name_seller,rating_seller,url,article,screen_diagonal,ram,os,internal_storage,screen_size,cpu,main_camera,matrix,type_of_tablet,brand,announcement_year,android_version,hz_screen,ppi,processor_brand,processor_cores,ghz_processor,brand_graphic_proccessor,video_processor,front_camera,keyboard,case_material,waterproof,battery_capacity,accessories_included,dimensions,weight_g,country_of_origin,ios_version,harmonyos_version
0,tablets,Hotwav Планшет TAB R9 Pro Планшет 11-дюймовый ...,84416.0,232764.0,7035.0,4.7,96.0,ИП Кулпеишова,4.4,https://www.ozon.kz/product/hotwav-planshet-ta...,2.135465e+09,11.0,6.0,Android,256.0,2504x1080,Tiger T606,64.0,IPS HD+,Планшет,Hotwav,2024.0,Android 14,120.0,350.0,Unisoc,8.0,1.6,ARM,Mali-G57 MP1,16.0,Опционально,"Металл, Полимер, Силикон, Стекло, Пластик",Да,20080.0,Стилус,300*200*20,1200.0,Китай,NaN,NaN
1,tablets,KENSHI Детский планшет KENSHI Kids E18 LTE 3/6...,79206.0,201339.0,6601.0,NaN,NaN,RS-Eectronics,4.9,https://www.ozon.kz/product/kenshi-detskiy-pla...,3.452295e+09,10.1,3.0,Android,64.0,1280x800,Tiger T310,NaN,IPS,Детский планшет,NaN,2023.0,Android 13.x,60.0,149.0,Unisoc,4.0,2.0,PowerVR,GT7200,0.3,NaN,Пластик,NaN,5000.0,NaN,257.5x206x9.5,528.0,Китай,NaN,NaN
2,tablets,"HUAWEI Планшет, 11"" 8 ГБ/128 ГБ, серый",NaN,NaN,9342.0,5.0,1.0,М.Видео,4.8,https://www.ozon.kz/product/huawei-planshet-11...,3.533774e+09,11.0,8.0,Другая,128.0,1920x1200,Kirin 710A,8.0,IPS,Планшет,NaN,NaN,NaN,NaN,NaN,HiSilicon,8.0,2.0,NaN,NaN,5.0,NaN,Металл,NaN,7700.0,Стилус,163.8x252.3x6.9,475.0,Китай,NaN,NaN
3,tablets,"Планшет Pad Galxay S25 Ultra, 10.1"" 16 ГБ/1024...",59896.0,322078.0,4992.0,5.0,70.0,YZ Store,4.9,https://www.ozon.kz/product/planshet-pad-galxa...,3.351633e+09,10.1,16.0,Android,1024.0,2560x1600,Snapdragon 8 Gen3 Leading Version,32.0,IPS,Планшет,NaN,2025.0,Android 15,140.0,NaN,Qualcomm,8.0,3.4,Qualcomm,Adreno 750,16.0,Опционально,"Металл, Пластик, Стекло",Да,10000.0,Клавиатура,214*160*8.7,300.0,Китай,NaN,NaN
4,tablets,Honor Планшет Honor Pad GT2 Pro игровой Snapdr...,244474.0,942238.0,20373.0,NaN,NaN,DigiMart Store,4.9,https://www.ozon.kz/product/honor-planshet-hon...,3.312049e+09,12.5,8.0,Android,128.0,3048x2032,Snapdragon 8 Gen3,13.0,LCD,Планшет,NaN,2025.0,Android 15,165.0,294.0,Qualcomm,8.0,3.3,Adreno,NaN,8.0,NaN,Металл,Да,10100.0,NaN,277.8 × 190.93 × 5.95 mm,580.0,Китай,NaN,NaN

In [398]:
# Диагностика столбцов для возможного удаления
n_rows = len(df3)
summary = pd.DataFrame({
    'null_count': df3.isna().sum(),
    'null_pct': (df3.isna().mean() * 100).round(2),
    'nunique': df3.nunique(dropna=False),
    'dtype': df3.dtypes.astype(str)
}).sort_values('null_pct', ascending=False)

print('Rows:', n_rows)
print('Columns:', df1.shape[1])
print('\nTop columns by null %:')
print(summary.head(20))

const_cols = summary[summary['nunique'] <= 1].index.tolist()
high_null_cols = summary[summary['null_pct'] >= 70].index.tolist()

print('\nConstant/near-constant cols (nunique <= 1):', const_cols)
print('High-null cols (>=70% NaN):', high_null_cols)

Rows: 5553
Columns: 33

Top columns by null %:
                          null_count  null_pct  nunique    dtype
harmonyos_version               5317     95.75        7   object
ios_version                     5174     93.17       14   object
brand                           4504     81.11       53   object
video_processor                 2826     50.89      113   object
accessories_included            2745     49.43        5   object
ppi                             2561     46.12      115  float64
keyboard                        2126     38.29        3   object
rating_card                     2116     38.11       33  float64
reviews_card                    2084     37.53      327  float64
hz_screen                       1722     31.01       12  float64
price                           1691     30.45     3116  float64
price_old                       1691     30.45     2583  float64
cpu                             1550     27.91      178   object
brand_graphic_proccessor        1508     27.16       15   object
waterproof                      1483     26.71        3   object
android_version                 1184     21.32       19   object
ghz_processor                   1052     18.94       76  float64
matrix                           906     16.32       40   object
country_of_origin                827     14.89       21   object
ram                              824     14.84       24  float64

Constant/near-constant cols (nunique <= 1): ['category']
High-null cols (>=70% NaN): ['harmonyos_version', 'ios_version', 'brand']

In [399]:
df3.drop(columns=['harmonyos_version','ios_version','brand','android_version'], inplace=True)

In [400]:
df3.isna().sum()

category                       0
name_card                    311
price                       1691
price_old                   1691
price_installment            332
rating_card                 2116
reviews_card                2084
name_seller                  311
rating_seller                368
url                            0
article                        3
screen_diagonal              313
ram                          824
os                           280
internal_storage             106
screen_size                  437
cpu                         1550
main_camera                  580
matrix                       906
type_of_tablet                 3
announcement_year            821
hz_screen                   1722
ppi                         2561
processor_brand              638
processor_cores              386
ghz_processor               1052
brand_graphic_proccessor    1508
video_processor             2826
front_camera                 688
keyboard                    2126
case_material                605
waterproof                  1483
battery_capacity             426
accessories_included        2745
dimensions                   478
weight_g                     351
country_of_origin            827
dtype: int64

In [401]:
num_cols_df3 = df3.select_dtypes(include=[np.number]).columns.tolist()
num_cols_df3

['price',
 'price_old',
 'price_installment',
 'rating_card',
 'reviews_card',
 'rating_seller',
 'article',
 'screen_diagonal',
 'ram',
 'internal_storage',
 'main_camera',
 'announcement_year',
 'hz_screen',
 'ppi',
 'processor_cores',
 'ghz_processor',
 'front_camera',
 'battery_capacity',
 'weight_g']

In [402]:
cat_cols_df3 = df3.select_dtypes(exclude=[np.number]).columns.tolist()
cat_cols_df3

['category',
 'name_card',
 'name_seller',
 'url',
 'os',
 'screen_size',
 'cpu',
 'matrix',
 'type_of_tablet',
 'processor_brand',
 'brand_graphic_proccessor',
 'video_processor',
 'keyboard',
 'case_material',
 'waterproof',
 'accessories_included',
 'dimensions',
 'country_of_origin']

In [403]:
num_cols_df3 = ['price','price_old','price_installment','rating_card','reviews_card','rating_seller','screen_diagonal','ram','internal_storage',
                'main_camera','announcement_year','hz_screen','ppi','processor_cores','ghz_processor','front_camera','battery_capacity','weight_g']

for col in num_cols_df3:
    df3[col] = df3[col].fillna(df3[col].median())

cat_cols_df3 = ['category','name_seller','os','screen_size','cpu','matrix','type_of_tablet','processor_brand','brand_graphic_proccessor',
                'video_processor','keyboard','case_material','waterproof','accessories_included','dimensions','country_of_origin']

for col in cat_cols_df3:
    df3[col] = df3[col].fillna('no_data')

In [404]:
df3.isna().sum()

category                      0
name_card                   311
price                         0
price_old                     0
price_installment             0
rating_card                   0
reviews_card                  0
name_seller                   0
rating_seller                 0
url                           0
article                       3
screen_diagonal               0
ram                           0
os                            0
internal_storage              0
screen_size                   0
cpu                           0
main_camera                   0
matrix                        0
type_of_tablet                0
announcement_year             0
hz_screen                     0
ppi                           0
processor_brand               0
processor_cores               0
ghz_processor                 0
brand_graphic_proccessor      0
video_processor               0
front_camera                  0
keyboard                      0
case_material                 0
waterproof                    0
battery_capacity              0
accessories_included          0
dimensions                    0
weight_g                      0
country_of_origin             0
dtype: int64

In [407]:
df1.head()

,category,name_card,price,price_old,price_installment,rating_card,reviews_card,name_seller,rating_seller,cpu,ssd_capacity,gpu_full_name,os,screen_diagonal,ram,auto_time,weight_kg,matrix,ram_type,case_material,cpu_model,processor_brand,ghz_processor,processor_cores,screen_size,touch_screen,battery_capacity,screen_coating,gpu_type,brand_graphic_proccessor,storage_type,hz_screen,web_camera
0,laptop,"MAIBENBEN Ноутбук 15.6"", Intel Core i5-12450H,...",424220.0,834731.0,25110.0,5.0,2.0,Sotomania,4.8,Intel Core i5-12450H,512.0,Intel UHD Graphics,Windows Pro,15.6,8.0,8.5,1.75,IPS,DDR4,Алюминий,Intel Core i5,Intel,2.0,8.0,1920x1080,Нет,69.3,no_data,no_data,no_data,no_data,60.0,2.0
1,laptop,"HUAWEI MateBook 14 FLMH-X Ноутбук 14.2"", Intel...",523339.0,2251014.0,43612.0,5.0,14.0,Фирменный магазин H...,4.9,Intel Core Ultra 5 125H,1024.0,Intel Arc Graphics,Без системы,14.2,16.0,19.0,1.31,OLED,LPDDR5,Алюминий,Intel Core Ultra 5,Intel,2.6,14.0,2880x1920,Да,70.0,Глянцевое,Встроенная,Intel,SSD,120.0,2.0
2,laptop,"Apple Ноутбук 11.6"", RAM 4 ГБ, SSD 128 ГБ, Mac...",424220.0,834731.0,27878.0,4.9,30.0,Comp+,4.9,no_data,128.0,no_data,MacOS,11.6,4.0,7.0,1.70,no_data,no_data,no_data,Intel Core i5,no_data,2.6,8.0,no_data,no_data,56.0,no_data,no_data,no_data,SSD,60.0,2.0
3,laptop,Ноутбук,424220.0,834731.0,19765.0,4.3,3.0,Полюс,4.9,no_data,512.0,no_data,no_data,15.6,16.0,7.0,1.70,no_data,no_data,no_data,no_data,no_data,2.6,8.0,no_data,no_data,56.0,no_data,no_data,no_data,no_data,60.0,2.0
4,laptop,"AMDR5 Ноутбук 15.6"", RAM 32 ГБ 2048 ГБ, AMD Ra...",257297.0,604910.0,21442.0,5.0,13.0,hassenda,4.8,no_data,2048.0,AMD Radeon,Windows Pro,15.6,32.0,7.0,1.70,no_data,DDR4,no_data,AMD Ryzen 5,AMD,2.0,4.0,1920x1080,no_data,80.0,no_data,no_data,AMD,no_data,120.0,5.0

In [408]:
df1['discount_abs'] = df1['price_old'] - df1['price']
df1['discount_pct'] = ((df1['price_old'] - df1['price']) / df1['price_old'] * 100).round(2)
df1['ram_per_core'] = df1['ram'] / df1['processor_cores']
df1['high_refresh_rate'] = df1['hz_screen'] >= 120
df1['cpu_power_proxy'] = df1['ghz_processor'] * df1['processor_cores']

In [ ]:
def safe_div(numerator, denominator):
    return numerator.div(denominator.replace(0, np.nan))

# Price/discount features
df2['discount_abs'] = df2['price_old'] - df2['price']
df2['discount_pct'] = safe_div(df2['discount_abs'], df2['price_old']) * 100

# Performance and value features
df2['cpu_power_proxy'] = df2['ghz_processor'] * df2['processor_cores']
df2['memory_per_price'] = safe_div(df2['built-in_memory'], df2['price'])
df2['ram_per_price'] = safe_div(df2['ram'], df2['price'])

# Camera features
df2['total_camera_mp'] = df2['main_camera'] + df2['front_camera']
df2['selfie_ratio'] = safe_div(df2['front_camera'], df2['main_camera'])

# Mobility feature
df2['battery_per_gram'] = safe_div(df2['battery_capacity'], df2['weight_g'])

# Binary flags
df2['high_fps_video'] = (df2['max_fps_video'] >= 60).astype(int)

esim_text = df2['e_sim'].astype(str).str.lower().str.strip()
df2['esim_flag'] = esim_text.str.contains('да|yes|true|есть|supported', regex=True).astype(int)

protect_text = df2['degree_of_protect'].astype(str).str.lower().str.strip()
df2['protection_flag'] = protect_text.str.contains('ip|защит|water|dust|влаг', regex=True).astype(int)

new_cols_df2 = [
    'discount_abs', 'discount_pct', 'cpu_power_proxy', 'memory_per_price',
    'ram_per_price', 'total_camera_mp', 'selfie_ratio', 'battery_per_gram',
    'high_fps_video', 'esim_flag', 'protection_flag'
]

df2[new_cols_df2].head()